packages:
  - packages/auth-server
  - packages/core
  - packages/electron-app
  - packages/web-app
  - packages/ytdlp-service
  - website
allowBuilds:
  core-js: set this to true or false
  electron: set this to true or false
  esbuild: set this to true or false
